name: Activity Types Workflow

on:
    pull_request:
        types: [opened, synchronize, closed, reopened]
        # types:
        #   - opened
        #   - synchronize
        #   - closed
        #   - reopened
        branches:
            - main  

jobs:
    activity-types-job:
        runs-on : ubuntu-latest
        steps:
            - run: 'echo "Activity Types Workflow is running for action: ${{ github.event.action }}"'

